-- Auto-generated by `npm run init:new-project`.
-- Apply this file to a fresh Supabase project to recreate the current schema and defaults.

-- ============================================================
-- Migration: 20240701_budget_management.sql
-- ============================================================
-- Budgets table
CREATE TABLE IF NOT EXISTS budgets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  total_amount numeric(12,2) NOT NULL,
  period_type text CHECK (period_type IN ('monthly', 'weekly', 'custom')) NOT NULL,
  start_date date NOT NULL,
  end_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  icon text,
  color text,
  is_default boolean DEFAULT false
);

-- BudgetCategories table
CREATE TABLE IF NOT EXISTS budget_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  budget_id uuid REFERENCES budgets(id) ON DELETE CASCADE NOT NULL,
  category_id uuid REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  allocated_amount numeric(12,2) NOT NULL
);

-- Transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  budget_id uuid REFERENCES budgets(id) ON DELETE CASCADE,
  category_id uuid REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  amount numeric(12,2) NOT NULL,
  description text,
  date timestamptz NOT NULL,
  type text CHECK (type IN ('expense', 'income')) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- AuditLogs table
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid,
  details jsonb,
  created_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Budgets policies
CREATE POLICY "Users can read own budgets"
  ON budgets
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own budgets"
  ON budgets
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own budgets"
  ON budgets
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own budgets"
  ON budgets
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Categories policies
CREATE POLICY "Users can read own categories"
  ON categories
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own categories"
  ON categories
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own categories"
  ON categories
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own categories"
  ON categories
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- BudgetCategories policies
CREATE POLICY "Users can read own budget_categories"
  ON budget_categories
  FOR SELECT
  TO authenticated
  USING (
    budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid())
  );

CREATE POLICY "Users can insert own budget_categories"
  ON budget_categories
  FOR INSERT
  TO authenticated
  WITH CHECK (
    budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid())
  );

CREATE POLICY "Users can update own budget_categories"
  ON budget_categories
  FOR UPDATE
  TO authenticated
  USING (
    budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid())
  )
  WITH CHECK (
    budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid())
  );

CREATE POLICY "Users can delete own budget_categories"
  ON budget_categories
  FOR DELETE
  TO authenticated
  USING (
    budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid())
  );

-- Transactions policies
CREATE POLICY "Users can read own transactions"
  ON transactions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own transactions"
  ON transactions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own transactions"
  ON transactions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own transactions"
  ON transactions
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- AuditLogs policies
CREATE POLICY "Users can read own audit_logs"
  ON audit_logs
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own audit_logs"
  ON audit_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_categories_user_id ON categories(user_id);
CREATE INDEX IF NOT EXISTS idx_budget_categories_budget_id ON budget_categories(budget_id);
CREATE INDEX IF NOT EXISTS idx_budget_categories_category_id ON budget_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_budget_id ON transactions(budget_id);
CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id); 

-- Insert default categories for all users
INSERT INTO categories (id, user_id, name, is_default)
SELECT gen_random_uuid(), u.id, c.name, true
FROM auth.users u
CROSS JOIN (VALUES
  ('Other'),
  ('Food & Dining'),
  ('Transportation'),
  ('Shopping'),
  ('Entertainment'),
  ('Utilities'),
  ('Healthcare'),
  ('Education'),
  ('Travel'),
  ('Housing'),
  ('Insurance'),
  ('Personal Care')
) AS c(name)
ON CONFLICT DO NOTHING;

-- ============================================================
-- Migration: 20250626094643_humble_coast.sql
-- ============================================================
/*
  # Credit Card Milestone Tracker Database Schema

  1. New Tables
    - `cards`
      - `id` (uuid, primary key)
      - `user_id` (uuid, foreign key to auth.users)
      - `card_company` (text)
      - `card_name` (text)
      - `card_network` (text)
      - `anniversary_month` (integer, 1-12)
      - `billing_date` (integer, 1-31)
      - `due_date` (integer, 1-31)
      - `annual_fee` (integer, in cents)
      - `milestone_amount` (integer, in cents)
      - `card_limit` (integer, in cents, nullable)
      - `created_at` (timestamp)
    
    - `monthly_spends`
      - `id` (uuid, primary key)
      - `card_id` (uuid, foreign key to cards.id)
      - `month` (text, format: YYYY-MM)
      - `year` (integer)
      - `amount_spent` (integer, in cents)
      - Unique constraint on (card_id, month, year)

  2. Security
    - Enable RLS on both tables
    - Add policies for authenticated users to access only their own data
*/

-- Create cards table
CREATE TABLE IF NOT EXISTS cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  card_company text NOT NULL,
  card_name text NOT NULL,
  card_network text NOT NULL,
  anniversary_month integer NOT NULL CHECK (anniversary_month >= 1 AND anniversary_month <= 12),
  billing_date integer NOT NULL CHECK (billing_date >= 1 AND billing_date <= 31),
  due_date integer NOT NULL CHECK (due_date >= 1 AND due_date <= 31),
  annual_fee integer NOT NULL DEFAULT 0,
  milestone_amount integer NOT NULL DEFAULT 0,
  card_limit integer,
  created_at timestamptz DEFAULT now()
);

-- Create monthly_spends table
CREATE TABLE IF NOT EXISTS monthly_spends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id uuid REFERENCES cards(id) ON DELETE CASCADE NOT NULL,
  month text NOT NULL,
  year integer NOT NULL,
  amount_spent integer NOT NULL DEFAULT 0,
  UNIQUE(card_id, month, year)
);

-- Enable Row Level Security
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_spends ENABLE ROW LEVEL SECURITY;

-- Cards policies
CREATE POLICY "Users can read own cards"
  ON cards
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own cards"
  ON cards
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own cards"
  ON cards
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own cards"
  ON cards
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Monthly spends policies
CREATE POLICY "Users can read own monthly spends"
  ON monthly_spends
  FOR SELECT
  TO authenticated
  USING (
    card_id IN (
      SELECT id FROM cards WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own monthly spends"
  ON monthly_spends
  FOR INSERT
  TO authenticated
  WITH CHECK (
    card_id IN (
      SELECT id FROM cards WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own monthly spends"
  ON monthly_spends
  FOR UPDATE
  TO authenticated
  USING (
    card_id IN (
      SELECT id FROM cards WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    card_id IN (
      SELECT id FROM cards WHERE user_id = auth.uid()
    )
  );

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_cards_user_id ON cards(user_id);
CREATE INDEX IF NOT EXISTS idx_monthly_spends_card_id ON monthly_spends(card_id);
CREATE INDEX IF NOT EXISTS idx_monthly_spends_month_year ON monthly_spends(month, year);

-- ============================================================
-- Migration: 20240702_add_payment_method_to_transactions.sql
-- ============================================================
-- Add payment_method and card_id to transactions
ALTER TABLE transactions ADD COLUMN payment_method text CHECK (payment_method IN ('credit_card', 'upi', 'cash', 'debit_card'));
ALTER TABLE transactions ADD COLUMN card_id uuid REFERENCES cards(id);

-- Optional: If you want to enforce that card_id is only set when payment_method is 'credit_card', you can add a check constraint (Postgres 12+):
-- ALTER TABLE transactions ADD CONSTRAINT card_id_only_for_credit_card CHECK (
--   (payment_method = 'credit_card' AND card_id IS NOT NULL) OR (payment_method != 'credit_card' AND card_id IS NULL) OR payment_method IS NULL
-- );

-- ============================================================
-- Migration: 20260619000100_default_categories_for_new_users.sql
-- ============================================================
-- Keep default budget categories available for every user, including users
-- created after the original budget migration was applied.

CREATE OR REPLACE FUNCTION public.create_default_categories_for_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.categories (user_id, name, is_default)
  SELECT NEW.id, default_category.name, true
  FROM (VALUES
    ('Other'),
    ('Food & Dining'),
    ('Transportation'),
    ('Shopping'),
    ('Entertainment'),
    ('Utilities'),
    ('Healthcare'),
    ('Education'),
    ('Travel'),
    ('Housing'),
    ('Insurance'),
    ('Personal Care')
  ) AS default_category(name)
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.categories existing
    WHERE existing.user_id = NEW.id
      AND lower(existing.name) = lower(default_category.name)
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_default_categories ON auth.users;

CREATE TRIGGER on_auth_user_created_default_categories
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.create_default_categories_for_user();

-- Backfill any missing default categories for existing users idempotently.
INSERT INTO public.categories (user_id, name, is_default)
SELECT users.id, default_category.name, true
FROM auth.users users
CROSS JOIN (VALUES
  ('Other'),
  ('Food & Dining'),
  ('Transportation'),
  ('Shopping'),
  ('Entertainment'),
  ('Utilities'),
  ('Healthcare'),
  ('Education'),
  ('Travel'),
  ('Housing'),
  ('Insurance'),
  ('Personal Care')
) AS default_category(name)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.categories existing
  WHERE existing.user_id = users.id
    AND lower(existing.name) = lower(default_category.name)
);

-- The frontend creates one budget per category and expects this column.
ALTER TABLE public.budgets
ADD COLUMN IF NOT EXISTS category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL;

UPDATE public.budgets budget
SET category_id = category.id
FROM public.categories category
WHERE budget.category_id IS NULL
  AND category.user_id = budget.user_id
  AND lower(category.name) = 'other';

ALTER TABLE public.budgets
ALTER COLUMN category_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_budgets_category_id ON public.budgets(category_id);

-- ============================================================
-- Migration: 20260730_captaintorch_integration.sql
-- ============================================================
-- ─── 1. Catalog Cards ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  bank TEXT NOT NULL,
  network TEXT,
  fee_type TEXT NOT NULL CHECK (fee_type IN ('LTF','FYF','paid')),
  fee_label TEXT,
  annual_fee INTEGER DEFAULT 0,
  joining_fee INTEGER DEFAULT 0,
  fee_waiver_spend INTEGER,
  fee_waiver_label TEXT,
  forex_markup TEXT,
  point_value TEXT,
  rewards_cycle TEXT,
  short_description TEXT,
  thumbnail_url TEXT,
  card_image_url TEXT,
  affiliate_url TEXT,
  full_review_slug TEXT,
  key_perks TEXT[] DEFAULT '{}',
  joining_benefits TEXT[] DEFAULT '{}',
  renewal_benefits TEXT[] DEFAULT '{}',
  earns_on TEXT[] DEFAULT '{}',
  does_not_earn_on TEXT[] DEFAULT '{}',
  lounge_access BOOLEAN DEFAULT false,
  lounge_domestic TEXT,
  lounge_international TEXT,
  is_featured BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  launched_at DATE DEFAULT CURRENT_DATE,
  last_updated_at TIMESTAMPTZ DEFAULT now(),
  update_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 2. Benefit Categories ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_benefit_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  icon TEXT,
  color TEXT DEFAULT 'gray'
);

-- ─── 3. Card ↔ Category ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_card_categories (
  card_id UUID REFERENCES catalog_cards(id) ON DELETE CASCADE,
  category_id UUID REFERENCES catalog_benefit_categories(id) ON DELETE CASCADE,
  PRIMARY KEY (card_id, category_id)
);

-- ─── 4. Offers ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id UUID REFERENCES catalog_cards(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  merchant TEXT,
  discount_value TEXT,
  min_transaction INTEGER DEFAULT 0,
  max_discount INTEGER,
  expiry_date DATE,
  no_end_date BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  affiliate_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 5. MCC Codes ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mcc_codes (
  mcc TEXT PRIMARY KEY,
  description TEXT NOT NULL,
  category TEXT,
  is_excluded_by_default BOOLEAN DEFAULT false
);

-- ─── 6. Card MCC Reward Rates ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_card_mcc_rewards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id UUID REFERENCES catalog_cards(id) ON DELETE CASCADE,
  mcc TEXT REFERENCES mcc_codes(mcc),
  reward_rate NUMERIC(5,2),
  reward_type TEXT DEFAULT 'points',
  cap_per_month NUMERIC,
  notes TEXT,
  UNIQUE (card_id, mcc)
);

-- ─── 7. Guides ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_guides (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  section TEXT NOT NULL CHECK (section IN ('merchants','rewards','hotels','airlines','lifestyle')),
  sub_section TEXT,
  summary TEXT,
  content TEXT,
  thumbnail_url TEXT,
  tags TEXT[] DEFAULT '{}',
  is_featured BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  launched_at DATE DEFAULT CURRENT_DATE,
  last_updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 8. Merchant Tips ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_merchant_tips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_name TEXT NOT NULL,
  merchant_slug TEXT UNIQUE NOT NULL,
  merchant_emoji TEXT DEFAULT '🏪',
  mcc TEXT REFERENCES mcc_codes(mcc),
  category TEXT,
  tip_text TEXT,
  full_tip TEXT,
  best_card_ids UUID[] DEFAULT '{}',
  exclusions TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 9. Articles ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  card_id UUID REFERENCES catalog_cards(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  author TEXT DEFAULT 'KYCc Team',
  published_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT now(),
  content TEXT,
  summary TEXT,
  thumbnail_url TEXT,
  tags TEXT[] DEFAULT '{}',
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 10. Hotel Programs ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_hotel_programs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  logo_url TEXT,
  description TEXT,
  benefits TEXT[] DEFAULT '{}',
  linked_card_ids UUID[] DEFAULT '{}',
  program_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 11. Airline Programs ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_airline_programs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  airline TEXT NOT NULL,
  logo_url TEXT,
  description TEXT,
  benefits TEXT[] DEFAULT '{}',
  linked_card_ids UUID[] DEFAULT '{}',
  program_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 12. Lifestyle Brands ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_lifestyle_brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category TEXT,
  logo_url TEXT,
  description TEXT,
  benefits TEXT[] DEFAULT '{}',
  linked_card_ids UUID[] DEFAULT '{}',
  brand_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 13. Calculator Configs ──────────────────────────────────────────────────
-- spend_categories shape: [{"name":"Utility","mccs":["4814","4900"],"rate":10,"cap_monthly":null,"type":"points"}]
-- tiers shape: [{"name":"Diamond","min_quarterly_spend":300000,"point_value_paise":100}]
CREATE TABLE IF NOT EXISTS catalog_calculator_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id UUID UNIQUE REFERENCES catalog_cards(id) ON DELETE CASCADE,
  spend_categories JSONB NOT NULL DEFAULT '[]',
  base_rate NUMERIC(5,2) DEFAULT 1.00,
  point_value_paise NUMERIC(8,4) DEFAULT 100,
  annual_fee INTEGER DEFAULT 0,
  fee_waiver_spend INTEGER,
  tiers JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 14. Weekly Updates / Changelog ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS catalog_card_updates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id UUID REFERENCES catalog_cards(id) ON DELETE CASCADE,
  update_type TEXT NOT NULL CHECK (update_type IN (
    'new_card','benefit_change','fee_change',
    'offer_update','merchant_tip','terms_change','mcc_update'
  )),
  headline TEXT NOT NULL,
  details TEXT,
  effective_date DATE DEFAULT CURRENT_DATE,
  is_significant BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_catalog_cards_slug     ON catalog_cards(slug);
CREATE INDEX IF NOT EXISTS idx_catalog_cards_bank     ON catalog_cards(bank);
CREATE INDEX IF NOT EXISTS idx_catalog_cards_featured ON catalog_cards(is_featured) WHERE is_featured = true;
CREATE INDEX IF NOT EXISTS idx_catalog_cards_launched ON catalog_cards(launched_at DESC);
CREATE INDEX IF NOT EXISTS idx_catalog_cards_updated  ON catalog_cards(last_updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_catalog_offers_card    ON catalog_offers(card_id);
CREATE INDEX IF NOT EXISTS idx_catalog_offers_expiry  ON catalog_offers(expiry_date);
CREATE INDEX IF NOT EXISTS idx_catalog_guides_section ON catalog_guides(section);
CREATE INDEX IF NOT EXISTS idx_catalog_merchant_slug  ON catalog_merchant_tips(merchant_slug);
CREATE INDEX IF NOT EXISTS idx_catalog_articles_slug  ON catalog_articles(slug);
CREATE INDEX IF NOT EXISTS idx_catalog_articles_card  ON catalog_articles(card_id);
CREATE INDEX IF NOT EXISTS idx_catalog_updates_card   ON catalog_card_updates(card_id);
CREATE INDEX IF NOT EXISTS idx_catalog_updates_date   ON catalog_card_updates(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mcc_category           ON mcc_codes(category);

-- ─── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE catalog_cards              ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_benefit_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_card_categories    ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_offers             ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcc_codes                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_card_mcc_rewards   ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_guides             ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_merchant_tips      ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_articles           ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_hotel_programs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_airline_programs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_lifestyle_brands   ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_calculator_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_card_updates       ENABLE ROW LEVEL SECURITY;

-- Drop existing select policies if they exist before creating
DROP POLICY IF EXISTS "auth_read_catalog_cards" ON catalog_cards;
CREATE POLICY "auth_read_catalog_cards"
  ON catalog_cards FOR SELECT TO authenticated USING (is_published = true);

DROP POLICY IF EXISTS "auth_read_catalog_benefit_categories" ON catalog_benefit_categories;
CREATE POLICY "auth_read_catalog_benefit_categories"
  ON catalog_benefit_categories FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_card_categories" ON catalog_card_categories;
CREATE POLICY "auth_read_catalog_card_categories"
  ON catalog_card_categories FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_offers" ON catalog_offers;
CREATE POLICY "auth_read_catalog_offers"
  ON catalog_offers FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_mcc_codes" ON mcc_codes;
CREATE POLICY "auth_read_mcc_codes"
  ON mcc_codes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_card_mcc_rewards" ON catalog_card_mcc_rewards;
CREATE POLICY "auth_read_catalog_card_mcc_rewards"
  ON catalog_card_mcc_rewards FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_guides" ON catalog_guides;
CREATE POLICY "auth_read_catalog_guides"
  ON catalog_guides FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_merchant_tips" ON catalog_merchant_tips;
CREATE POLICY "auth_read_catalog_merchant_tips"
  ON catalog_merchant_tips FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_articles" ON catalog_articles;
CREATE POLICY "auth_read_catalog_articles"
  ON catalog_articles FOR SELECT TO authenticated USING (is_published = true);

DROP POLICY IF EXISTS "auth_read_catalog_hotel_programs" ON catalog_hotel_programs;
CREATE POLICY "auth_read_catalog_hotel_programs"
  ON catalog_hotel_programs FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_airline_programs" ON catalog_airline_programs;
CREATE POLICY "auth_read_catalog_airline_programs"
  ON catalog_airline_programs FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_lifestyle_brands" ON catalog_lifestyle_brands;
CREATE POLICY "auth_read_catalog_lifestyle_brands"
  ON catalog_lifestyle_brands FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_calculator_configs" ON catalog_calculator_configs;
CREATE POLICY "auth_read_catalog_calculator_configs"
  ON catalog_calculator_configs FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_read_catalog_card_updates" ON catalog_card_updates;
CREATE POLICY "auth_read_catalog_card_updates"
  ON catalog_card_updates FOR SELECT TO authenticated USING (true);

-- ─── Seed: Benefit Categories ────────────────────────────────────────────────
INSERT INTO catalog_benefit_categories (name, icon, color) VALUES
  ('Apparel','👗','pink'), ('Utility','⚡','yellow'), ('Grocery','🛒','green'),
  ('Online','🛍️','purple'), ('Travel','✈️','blue'), ('Dining','🍽️','orange'),
  ('International','🌍','teal'), ('Hotels','🏨','indigo'),
  ('Fuel','⛽','red'), ('Entertainment','🎬','violet'), ('Fitness','💪','lime')
ON CONFLICT (name) DO NOTHING;

-- ─── Seed: MCC Codes ─────────────────────────────────────────────────────────
INSERT INTO mcc_codes (mcc, description, category) VALUES
  ('4121','Taxicabs and Limousines (Uber, Ola)','transport'),
  ('4814','Telecommunication Services (Vi, Jio, Airtel)','utilities'),
  ('4816','Computer Network Services','utilities'),
  ('4829','Money Transfer','finance'),
  ('4900','Electric, Gas, Water Utilities','utilities'),
  ('5045','Computers, Peripherals, Software','electronics'),
  ('5262','Marketplaces (Amazon, Flipkart)','online'),
  ('5311','Department Stores','apparel'),
  ('5399','Misc General Merchandise','grocery'),
  ('5411','Grocery Stores, Supermarkets','grocery'),
  ('5441','Candy, Nut, Confectionery Stores','grocery'),
  ('5451','Dairy Products Stores','grocery'),
  ('5462','Bakeries','dining'),
  ('5499','Misc Food Stores','grocery'),
  ('5541','Service Stations (Fuel)','fuel'),
  ('5542','Automated Fuel Dispensers','fuel'),
  ('5611','Men''s and Boy''s Clothing','apparel'),
  ('5621','Women''s Ready-to-Wear','apparel'),
  ('5631','Women''s Accessory Shops','apparel'),
  ('5641','Children''s and Infants'' Wear','apparel'),
  ('5651','Family Clothing Stores (Ajio — RELIANCE RETAIL LTD)','apparel'),
  ('5655','Sports and Riding Apparel','apparel'),
  ('5691','Men''s and Women''s Clothing (Myntra, Ajio alt)','apparel'),
  ('5699','Misc Apparel — often NOT eligible for 5X','apparel'),
  ('5732','Electronics Sales','electronics'),
  ('5812','Eating Places and Restaurants','dining'),
  ('5814','Fast Food Restaurants','dining'),
  ('5912','Drug Stores, Pharmacies','health'),
  ('6012','Member Financial Institutions','finance'),
  ('6051','Non-Financial Institutions','finance'),
  ('6513','Real Estate Agents and Managers','real_estate'),
  ('7011','Hotels, Motels, Resorts','hotels'),
  ('7832','Motion Picture Theaters','entertainment'),
  ('8011','Doctors and Physicians','health'),
  ('8099','Health Practitioners','health')
ON CONFLICT (mcc) DO NOTHING;

UPDATE mcc_codes SET is_excluded_by_default = true
WHERE mcc IN ('4829','6012','6051','6513');

-- ============================================================
-- Migration: 20260730_scaling.sql
-- ============================================================
-- Add month column to budgets
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS month text;

-- Transactions (most queried table)
CREATE INDEX IF NOT EXISTS idx_transactions_user_id       ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_created  ON transactions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_card_created  ON transactions(card_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at    ON transactions(created_at DESC);

-- Cards
CREATE INDEX IF NOT EXISTS idx_cards_user_id              ON cards(user_id);

-- Budgets
CREATE INDEX IF NOT EXISTS idx_budgets_user_id            ON budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_budgets_user_month         ON budgets(user_id, month);

-- Categories
CREATE INDEX IF NOT EXISTS idx_categories_user_id         ON categories(user_id);

-- Other tables from migrations
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id         ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_budget_categories_budget_id ON budget_categories(budget_id);

-- Enable RLS if not already enabled
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_spends ENABLE ROW LEVEL SECURITY;

-- Ensure all 4 operation policies exist, scoped to auth.uid()
-- cards
DO $$ BEGIN
  CREATE POLICY "users_select_own_cards" ON cards FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_cards" ON cards FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_cards" ON cards FOR UPDATE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_cards" ON cards FOR DELETE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- transactions
DO $$ BEGIN
  CREATE POLICY "users_select_own_transactions" ON transactions FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_transactions" ON transactions FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_transactions" ON transactions FOR UPDATE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_transactions" ON transactions FOR DELETE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- budgets
DO $$ BEGIN
  CREATE POLICY "users_select_own_budgets" ON budgets FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_budgets" ON budgets FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_budgets" ON budgets FOR UPDATE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_budgets" ON budgets FOR DELETE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- categories
DO $$ BEGIN
  CREATE POLICY "users_select_own_categories" ON categories FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_categories" ON categories FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_categories" ON categories FOR UPDATE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_categories" ON categories FOR DELETE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- audit_logs
DO $$ BEGIN
  CREATE POLICY "users_select_own_audit_logs" ON audit_logs FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_audit_logs" ON audit_logs FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_audit_logs" ON audit_logs FOR UPDATE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_audit_logs" ON audit_logs FOR DELETE TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- budget_categories (has no user_id, check through budget_id)
DO $$ BEGIN
  CREATE POLICY "users_select_own_budget_categories" ON budget_categories FOR SELECT TO authenticated USING (budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_budget_categories" ON budget_categories FOR INSERT TO authenticated WITH CHECK (budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_budget_categories" ON budget_categories FOR UPDATE TO authenticated USING (budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_budget_categories" ON budget_categories FOR DELETE TO authenticated USING (budget_id IN (SELECT id FROM budgets WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- monthly_spends (has no user_id, check through card_id)
DO $$ BEGIN
  CREATE POLICY "users_select_own_monthly_spends" ON monthly_spends FOR SELECT TO authenticated USING (card_id IN (SELECT id FROM cards WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_insert_own_monthly_spends" ON monthly_spends FOR INSERT TO authenticated WITH CHECK (card_id IN (SELECT id FROM cards WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_update_own_monthly_spends" ON monthly_spends FOR UPDATE TO authenticated USING (card_id IN (SELECT id FROM cards WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "users_delete_own_monthly_spends" ON monthly_spends FOR DELETE TO authenticated USING (card_id IN (SELECT id FROM cards WHERE user_id = auth.uid()));
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- AI usage tracking + rate limiting
CREATE TABLE IF NOT EXISTS ai_usage (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  function_name TEXT NOT NULL,
  tokens_used   INTEGER DEFAULT 0,
  cost_usd      NUMERIC(10,6) DEFAULT 0,
  created_at    TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "users_read_own_ai_usage" ON ai_usage FOR SELECT TO authenticated USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE INDEX IF NOT EXISTS idx_ai_usage_user_fn_created
  ON ai_usage(user_id, function_name, created_at DESC);

-- Rate limit check function
CREATE OR REPLACE FUNCTION check_ai_rate_limit(
  p_user_id       UUID,
  p_function_name TEXT,
  p_daily_limit   INTEGER DEFAULT 10
) RETURNS BOOLEAN
LANGUAGE sql SECURITY DEFINER AS $inner$
  SELECT COUNT(*) < p_daily_limit
  FROM ai_usage
  WHERE user_id       = p_user_id
    AND function_name = p_function_name
    AND created_at    > NOW() - INTERVAL '24 hours';
$inner$;
