-- =============================================================================
-- PHASE 4A: Card ↔ Benefit Category Mappings
-- =============================================================================

INSERT INTO catalog_card_categories (card_id, category_id)
SELECT c.id, cat.id
FROM (
  VALUES
  ('equitas-selfe', 'Apparel'),
  ('equitas-selfe', 'Utility'),
  ('equitas-selfe', 'Grocery'),
  ('bob-eterna', 'Online'),
  ('bob-eterna', 'Travel'),
  ('bob-eterna', 'Dining'),
  ('bob-eterna', 'International'),
  ('hdfc-marriott-bonvoy', 'Hotels'),
  ('hdfc-marriott-bonvoy', 'Travel'),
  ('hdfc-marriott-bonvoy', 'Dining'),
  ('hdfc-regalia-gold', 'Travel'),
  ('hdfc-regalia-gold', 'Hotels'),
  ('hdfc-regalia-gold', 'Lifestyle'),
  ('hdfc-regalia-gold', 'Shopping'),
  ('yes-reserv', 'Online'),
  ('yes-reserv', 'Travel'),
  ('yes-reserv', 'Apparel'),
  ('yes-reserv', 'Dining'),
  ('yes-reserv', 'International'),
  ('scapia', 'Travel'),
  ('scapia', 'Everyday Retail'),
  ('scapia', 'Gold & Jewelry'),
  ('amex-platinum-charge', 'Travel'),
  ('amex-platinum-charge', 'International'),
  ('amex-platinum-charge', 'Luxury'),
  ('times-black-icici', 'International'),
  ('times-black-icici', 'Travel'),
  ('times-black-icici', 'Lifestyle'),
  ('times-black-icici', 'All Retail'),
  ('au-lit', 'Retail'),
  ('au-lit', 'Grocery'),
  ('au-lit', 'Apparel'),
  ('au-lit', 'Online'),
  ('sbi-cashback', 'Online'),
  ('sbi-cashback', 'Shopping'),
  ('sbi-cashback', 'Grocery'),
  ('sbi-cashback', 'Dining'),
  ('sbi-cashback', 'Travel'),
  ('sbi-phonepe-select-black', 'PhonePe'),
  ('sbi-phonepe-select-black', 'Online Shopping'),
  ('sbi-phonepe-select-black', 'UPI'),
  ('sbi-phonepe-select-black', 'Travel'),
  ('sbi-phonepe-select-black', 'Utilities'),
  ('hdfc-swiggy', 'Food Delivery'),
  ('hdfc-swiggy', 'Grocery'),
  ('hdfc-swiggy', 'Dining'),
  ('hdfc-swiggy', 'Online Shopping'),
  ('hdfc-swiggy', 'Travel'),
  ('hdfc-swiggy', 'Transport'),
  ('axis-cashback', 'Online'),
  ('axis-cashback', 'Shopping'),
  ('axis-cashback', 'Utilities'),
  ('axis-magnus', 'Travel'),
  ('axis-magnus', 'Miles Transfer'),
  ('axis-magnus', 'Lifestyle'),
  ('axis-magnus', 'International'),
  ('axis-magnus-burgundy', 'Travel'),
  ('axis-magnus-burgundy', 'Miles Transfer'),
  ('axis-magnus-burgundy', 'Dining'),
  ('axis-magnus-burgundy', 'Lifestyle'),
  ('hsbc-live-plus', 'Dining'),
  ('hsbc-live-plus', 'Food Delivery'),
  ('hsbc-live-plus', 'Groceries'),
  ('bob-etihad-guest-premium', 'Travel'),
  ('bob-etihad-guest-premium', 'International'),
  ('bob-etihad-guest-premium', 'Airline Miles'),
  ('salaryse-levelup', 'UPI'),
  ('salaryse-levelup', 'Everyday Spends'),
  ('salaryse-levelup', 'Gift Cards'),
  ('icici-amazon-pay', 'Amazon'),
  ('icici-amazon-pay', 'Online'),
  ('icici-amazon-pay', 'Grocery'),
  ('icici-amazon-pay', 'Shopping'),
  ('axis-ace', 'Utilities'),
  ('axis-ace', 'Dining'),
  ('axis-ace', 'Travel'),
  ('axis-ace', 'Online'),
  ('axis-ace', 'Offline'),
  ('axis-flipkart', 'Flipkart'),
  ('axis-flipkart', 'Myntra'),
  ('axis-flipkart', 'Cleartrip'),
  ('axis-flipkart', 'Dining'),
  ('axis-flipkart', 'Entertainment'),
  ('idfc-first-wealth', 'Online'),
  ('idfc-first-wealth', 'Dining'),
  ('idfc-first-wealth', 'Travel'),
  ('idfc-first-wealth', 'Retail'),
  ('idfc-first-wealth', 'International'),
  ('sc-ultimate', 'All Retail'),
  ('sc-ultimate', 'Online'),
  ('sc-ultimate', 'Dining'),
  ('sc-ultimate', 'Travel'),
  ('sc-ultimate', 'International'),
  ('hdfc-millennia', 'Amazon'),
  ('hdfc-millennia', 'Flipkart'),
  ('hdfc-millennia', 'Myntra'),
  ('hdfc-millennia', 'Dining'),
  ('hdfc-millennia', 'Travel'),
  ('hdfc-millennia', 'Entertainment'),
  ('hdfc-diners-black', 'Travel'),
  ('hdfc-diners-black', 'Hotels'),
  ('hdfc-diners-black', 'Dining'),
  ('hdfc-diners-black', 'Lifestyle'),
  ('hdfc-diners-black', 'International'),
  ('hdfc-diners-privilege', 'Travel'),
  ('hdfc-diners-privilege', 'Hotels'),
  ('hdfc-diners-privilege', 'Lifestyle'),
  ('hdfc-tata-neu-infinity', 'Tata Brands'),
  ('hdfc-tata-neu-infinity', 'Grocery'),
  ('hdfc-tata-neu-infinity', 'Travel'),
  ('hdfc-tata-neu-infinity', 'Electronics'),
  ('hdfc-tata-neu-infinity', 'Health'),
  ('hdfc-moneyback-plus', 'Amazon'),
  ('hdfc-moneyback-plus', 'Flipkart'),
  ('hdfc-moneyback-plus', 'Food Delivery'),
  ('hdfc-moneyback-plus', 'Grocery'),
  ('hdfc-indianoil', 'Fuel'),
  ('hdfc-indianoil', 'Grocery'),
  ('hdfc-indianoil', 'Dining'),
  ('sbi-aurum', 'Travel'),
  ('sbi-aurum', 'Lifestyle'),
  ('sbi-aurum', 'Dining'),
  ('sbi-aurum', 'International'),
  ('sbi-elite', 'Dining'),
  ('sbi-elite', 'Grocery'),
  ('sbi-elite', 'Shopping'),
  ('sbi-elite', 'Travel'),
  ('sbi-prime', 'Dining'),
  ('sbi-prime', 'Grocery'),
  ('sbi-prime', 'Shopping'),
  ('sbi-simplyclick', 'Amazon'),
  ('sbi-simplyclick', 'Food Delivery'),
  ('sbi-simplyclick', 'Travel'),
  ('sbi-simplyclick', 'Entertainment'),
  ('sbi-simplyclick', 'Online'),
  ('sbi-simplysave', 'Dining'),
  ('sbi-simplysave', 'Entertainment'),
  ('sbi-simplysave', 'Grocery'),
  ('sbi-simplysave', 'Shopping'),
  ('sbi-bpcl-octane', 'Fuel'),
  ('sbi-bpcl-octane', 'Grocery'),
  ('sbi-bpcl-octane', 'Dining'),
  ('sbi-bpcl-octane', 'Entertainment'),
  ('hdfc-infinia', 'Travel'),
  ('hdfc-infinia', 'Hotels'),
  ('hdfc-infinia', 'Lifestyle'),
  ('hdfc-infinia', 'Shopping'),
  ('hdfc-infinia', 'International'),
  ('icici-emeralde-private-metal', 'All Retail'),
  ('icici-emeralde-private-metal', 'Travel'),
  ('icici-emeralde-private-metal', 'Dining'),
  ('icici-emeralde-private-metal', 'International'),
  ('icici-emeralde', 'All Retail'),
  ('icici-emeralde', 'Travel'),
  ('icici-emeralde', 'Dining'),
  ('icici-emeralde', 'Shopping'),
  ('icici-sapphiro', 'Travel'),
  ('icici-sapphiro', 'Dining'),
  ('icici-sapphiro', 'Shopping'),
  ('icici-coral', 'Shopping'),
  ('icici-coral', 'Dining'),
  ('icici-coral', 'Entertainment'),
  ('icici-hpcl-super-saver', 'Fuel'),
  ('icici-hpcl-super-saver', 'Grocery'),
  ('icici-hpcl-super-saver', 'Utility'),
  ('axis-reserve', 'Travel'),
  ('axis-reserve', 'International'),
  ('axis-reserve', 'Lifestyle'),
  ('axis-reserve', 'Dining'),
  ('axis-select', 'Travel'),
  ('axis-select', 'Shopping'),
  ('axis-select', 'Entertainment'),
  ('axis-privilege', 'Travel'),
  ('axis-privilege', 'Entertainment'),
  ('axis-privilege', 'Shopping'),
  ('axis-neo', 'Fashion'),
  ('axis-neo', 'Food Delivery'),
  ('axis-neo', 'Dining'),
  ('axis-indianoil', 'Fuel'),
  ('axis-indianoil', 'Grocery'),
  ('axis-airtel', 'Telecom'),
  ('axis-airtel', 'Food Delivery'),
  ('axis-airtel', 'Grocery'),
  ('axis-atlas', 'Travel'),
  ('axis-atlas', 'Dining'),
  ('axis-atlas', 'Online'),
  ('axis-atlas', 'International'),
  ('kotak-white-reserve', 'Travel'),
  ('kotak-white-reserve', 'Lifestyle'),
  ('kotak-white-reserve', 'Shopping'),
  ('kotak-white-reserve', 'International'),
  ('kotak-cashback-plus', 'Grocery'),
  ('kotak-cashback-plus', 'Food Delivery'),
  ('kotak-cashback-plus', 'Entertainment'),
  ('kotak-cashback-plus', 'Fuel'),
  ('kotak-league-platinum', 'All Retail'),
  ('kotak-league-platinum', 'Online'),
  ('kotak-league-platinum', 'Offline'),
  ('yes-private', 'Online'),
  ('yes-private', 'Travel'),
  ('yes-private', 'Dining'),
  ('yes-private', 'Lifestyle'),
  ('yes-private', 'International'),
  ('yes-marquee', 'Online'),
  ('yes-marquee', 'Travel'),
  ('yes-marquee', 'Dining'),
  ('yes-marquee', 'International'),
  ('yes-premia', 'Online'),
  ('yes-premia', 'Shopping'),
  ('yes-premia', 'Dining'),
  ('idfc-first-select', 'Online'),
  ('idfc-first-select', 'Dining'),
  ('idfc-first-select', 'Retail'),
  ('idfc-first-select', 'International'),
  ('idfc-first-millennia', 'Online'),
  ('idfc-first-millennia', 'Entertainment'),
  ('idfc-first-millennia', 'Dining'),
  ('idfc-first-millennia', 'Retail'),
  ('idfc-first-power-hpcl', 'Fuel'),
  ('idfc-first-power-hpcl', 'Grocery'),
  ('idfc-first-power-hpcl', 'Utility'),
  ('indusind-pinnacle', 'Travel'),
  ('indusind-pinnacle', 'International'),
  ('indusind-pinnacle', 'Lifestyle'),
  ('indusind-pinnacle', 'Shopping'),
  ('indusind-legend', 'All Retail'),
  ('indusind-legend', 'Dining'),
  ('indusind-legend', 'Shopping'),
  ('indusind-legend', 'Travel'),
  ('indusind-platinum-aura-edge', 'All Retail'),
  ('indusind-platinum-aura-edge', 'Online'),
  ('indusind-platinum-aura-edge', 'Offline'),
  ('rbl-icon', 'Dining'),
  ('rbl-icon', 'Shopping'),
  ('rbl-icon', 'Travel'),
  ('rbl-nova', 'Travel'),
  ('rbl-nova', 'Lifestyle'),
  ('rbl-nova', 'Dining'),
  ('rbl-lumiere', 'Travel'),
  ('rbl-lumiere', 'Lifestyle'),
  ('sc-smart', 'Online'),
  ('sc-smart', 'All Retail'),
  ('sc-smart', 'Shopping'),
  ('sc-emirates', 'Travel'),
  ('sc-emirates', 'International'),
  ('sc-emirates', 'Emirates'),
  ('sc-emirates', 'Shopping'),
  ('federal-celesta', 'Travel'),
  ('federal-celesta', 'Lifestyle'),
  ('federal-celesta', 'Shopping'),
  ('federal-signet', 'All Retail'),
  ('federal-signet', 'Online'),
  ('federal-signet', 'Offline'),
  ('bob-premier', 'Travel'),
  ('bob-premier', 'Dining'),
  ('bob-premier', 'International'),
  ('bob-select', 'Online'),
  ('bob-select', 'Utility'),
  ('bob-select', 'Dining'),
  ('bob-cashback', 'Online'),
  ('bob-cashback', 'Shopping'),
  ('bob-cashback', 'Dining'),
  ('bob-cashback', 'Travel'),
  ('amex-platinum-travel', 'Travel'),
  ('amex-platinum-travel', 'Milestones'),
  ('amex-platinum-travel', 'Hotels'),
  ('amex-mrcc', 'Shopping'),
  ('amex-mrcc', 'Milestones'),
  ('amex-mrcc', 'Everyday Retail'),
  ('hdfc-tata-neu-plus', 'Tata Brands'),
  ('hdfc-tata-neu-plus', 'Grocery'),
  ('hdfc-tata-neu-plus', 'UPI'),
  ('hdfc-tata-neu-plus', 'Shopping'),
  ('axis-myzone', 'Dining'),
  ('axis-myzone', 'Entertainment'),
  ('axis-myzone', 'Shopping'),
  ('rbl-world-safari', 'Travel'),
  ('rbl-world-safari', 'Airlines'),
  ('rbl-world-safari', 'Hotels'),
  ('rbl-world-safari', 'International'),
  ('axis-horizon', 'Travel'),
  ('axis-horizon', 'Airlines'),
  ('kotak-air-plus', 'Travel'),
  ('kotak-air-plus', 'Hotels'),
  ('indusind-tiger', 'All eligible spends')
) AS t(card_slug, cat_name)
JOIN catalog_cards c ON c.slug = t.card_slug
JOIN catalog_benefit_categories cat ON LOWER(cat.name) = LOWER(t.cat_name)
ON CONFLICT (card_id, category_id) DO NOTHING;
